### ISSUE TITLE
Random Guess？

### ISSUE THREAD

**Issue by hongliang-wei** [zhourax/VEGA#1]
Thanks for your hard work. Could you explain what the Random Guess settings are in Table 2?

**Comment by zhourax** [comment]
Thank you for your attention. The setting of Random Guess is designed to intuitively reflect the difficulty of the task. In the IITC Task, Random Guess = 1/(average number of images), and in the ITA Task, since it can be considered a ranking task, Random Guess = 1/(P(n, n)), where n is the number of images.
